# Generated by Django 5.2.5 on 2025-08-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('duration_limit', models.IntegerField(help_text='Max duration in minutes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
